per_device_train_batch_size: 8
learning_rate: 5e-5
weight_decay: 0.0
num_train_epochs: 3
max_train_steps: null
gradient_accumulation_steps: 4
lr_scheduler_type: "linear"
num_warmup_steps: 0
output_dir: "runs"
seed: 42
block_size: 2048
preprocessing_num_workers: 8
overwrite_cache: false
no_keep_linebreaks: false
push_to_hub: false
hub_model_id: null
hub_token: null
trust_remote_code: false
checkpointing_steps: null
resume_from_checkpoint: null
with_tracking: true
report_to: "wandb"
low_cpu_mem_usage: false
model_name : naver-clova-ix/donut-base-finetuned-cord-v2
data_kwargs:
  csv_path : clean_data.csv
  pdf_folder_path : dataset